accounts/urls.py
from django.urls import path
from .  import views
urlpatterns = [
    path('register/',views.register ,name='register'),
    path('login/',views.log_in ,name='login'),
    path('logout/',views.log_out ,name='logout'),
    path('', views.dashboard, name = "dashboard"),

    path('activate/<str:uidb64>/<str:token>/',views.activate,name="activate"),
    path('forgotpassword/',views.forgotpassword,name='forgotpassword'),
    path('resetpassword/<str:uidb64>/<str:token>/', views.resetpassword_validate, name="resetpassword_validate"),
    path('resetpassword/',views.resetpassword,name='resetpassword'),

    path('my_orders/',views.my_orders, name = "my_orders"),
    path('edit_profile/',views.edit_profile, name = "edit_profile"),
    path('change_password/', views.change_password, name = "change_password"),
    path('order_detail/<int:order_id>/',views.order_detail, name="order_detail"),
    path('cancel_order/<int:order_id>/',views.cancel_order,name="cancel_order_confirmation"),
    path('return_order/<int:order_id>/',views.return_order, name="return_order"),

    path('add_address/', views.add_address, name="add_address"),
    path('ajax_load_district',views.ajax_load_district, name ='ajax_load_district'),
    path('edit_address/<int:address_id>/', views.edit_address, name="edit_address"),
    path('delete_address/<int:address_id>/', views.delete_address, name="delete_address"),

    path('wallet/',views.wallet, name = "wallet"),
    path('wallet/wallet_transaction/',views.wallet_transaction,name = "wallet_transaction")
 

]

estilo/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home,name="home"),
    path('shop/',include('shop.urls')),
    path('accounts/',include('accounts.urls')),
    path('admin_panel/',include('admin_panel.urls')),
    path('carts/',include('scarts.urls')),
    path('orders/',include('orders.urls')),
] 
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_URL)

shop/urls.py
from django.urls import path
from .  import views
urlpatterns = [
    path('',views.list_products ,name='shop'),
    path('category/<slug:category_slug>/',views.list_products ,name='products_by_category'),
    path('product/<slug:category_slug>/<slug:product_slug>/',views.product_detail, name='product_detail'),
    path('search/',views.search,name="search"),
    path('filter_products/',views.filter_products, name="filter_products"),
    path('shop_latest/',views.shop_latest,name="shop_latest"),
    path('add_wishlist/<int:product_id>/', views.add_wishlist , name="add_wishlist"),
    path('wishlist/', views.wishlist, name="wishlist"),
    path('delete_wishlist/<int:wishlist_id>/',views.delete_wishlist, name ="delete_wishlist"),
    path('get_available_colors/',views.get_available_colors,name="get_available_colors"),
    path('low_to_high/',views.low_to_high,name="low_to_high"),
    path('high_to_low/',views.high_to_low, name="high_to_low"),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.contrib.auth.models import BaseUserManager
from django.core.validators import MinLengthValidator


class CustomUserManager(BaseUserManager):
    def create_user(self, email, password=None, **extra_fields):
        if not email:
            raise ValueError('The Email field must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.is_active = False  # Set is_active to False by default
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        extra_fields.setdefault('is_active', True)

        return self.create_user(email, password, **extra_fields)


class Account(AbstractUser):
    first_name=models.CharField(max_length=50)
    last_name=models.CharField(max_length=50)
    email=models.EmailField(max_length=100,unique=True)
    username=models.CharField(max_length=50,unique=True)
    is_blocked = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add = True)

    USERNAME_FIELD='email'
    REQUIRED_FIELDS=['username']
    objects=CustomUserManager()

    def full_name(self):
        return f"{self.first_name.capitalize()} {self.last_name.capitalize()}"
    
    def __str__(self):
        return self.username
    
class UserProfile(models.Model):
    user = models.OneToOneField(Account, on_delete = models.CASCADE)
    profile_picture = models.ImageField(blank = True, upload_to ='profile_picture')
    phone = models.CharField(max_length = 20,blank = True)
  
    def __str__(self):
        return self.user.first_name    


class State(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name

class District(models.Model):
    name = models.CharField(max_length=50)
    state = models.ForeignKey(State, on_delete=models.CASCADE)

    def __str__(self):
        return self.name
    
class Address(models.Model):
    
    user= models.ForeignKey(Account, on_delete=models.CASCADE)
    address_line_1 = models.CharField(max_length=100)
    address_line_2 = models.CharField(max_length=100, blank=True)
    country = models.CharField(max_length=50, default='India')
    state = models.ForeignKey(State, on_delete=models.SET_NULL, blank = True, null = True)
    district = models.ForeignKey(District, on_delete=models.SET_NULL, blank = True, null = True)
    postal_code = models.CharField(max_length=20)

    def full_address(self):
        return f"{self.address_line_1} {self.address_line_2},{self.country}, {self.state},{self.district}, {self.postal_code}"

    def __str__(self):
        return f"{self.address_line_1}, {self.district}, {self.state}, {self.country}"

orders/models.py
from django.db import models
from accounts.models import Account,UserProfile,Address
from shop.models import Product, ProductAttribute
from django.utils import timezone
import secrets
import string
from datetime import date

# Create your models here.

class Payment(models.Model):
    PAYMENT_STATUS = (
        ('', ''),
        ('Pending', 'Pending'),
        ('Paid','Paid'),
        ('Failed','Failed'),
    )
    user = models.ForeignKey(Account, on_delete = models.CASCADE)
    payment_id = models.CharField(max_length = 100)
    payment_method = models.CharField(max_length=20)  
    amount_paid = models.PositiveIntegerField()
    status = models.CharField(max_length = 100,choices=PAYMENT_STATUS)
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(default=timezone.now)


    def __str__(self):
        return self.payment_id
    

# Create your models here.
class Coupon(models.Model):
    coupon_code = models.CharField(max_length=50, unique=True)
    discount = models.PositiveIntegerField(default = 50)
    expiration_date = models.DateField()
    max_usage = models.PositiveIntegerField(default=1)
    used_count = models.PositiveIntegerField(default=0)
    minimum_amount = models.PositiveIntegerField(default=500)
    active = models.BooleanField(default = True)

    @staticmethod
    def generate_coupon_code(length=10):
        characters = string.ascii_letters + string.digits
        coupon_code = ''.join(secrets.choice(characters) for _ in range(length))
        return coupon_code.upper()
    
    def is_valid(self):
        return self.expiration_date >= date.today() and self.used_count < self.max_usage
    
    def is_used_by_user(self, user):
        redeemed_details = UserCoupons.objects.filter(coupon=self, user=user, is_used=True)
        return redeemed_details.exists()

    def __str__(self):
        return self.coupon_code

class UserCoupons(models.Model):
    user = models.ForeignKey(Account, on_delete=models.CASCADE, null=True)
    coupon = models.ForeignKey(Coupon, on_delete=models.CASCADE)
    is_used = models.BooleanField(default=True)

    def __str__(self):
        return self.coupon.coupon_code

class Order(models.Model):
    STATUS = (
        ('Pending', 'Pending'),
        ('Accepted','Accepted'),
        ('Shipped','Shipped'),
        ('Out For Delivery','Out For Delivery'),
        ('Delivered','Delivered'),
        ('Cancelled', 'Cancelled'),
        ('Returned','Returned')
    )

    CANCELLATION_REASONS = (
        ('No Longer Needed', 'No Longer Needed'),
        ('Ordered By Mistake', 'Ordered By Mistake'),
        ('Changed Mind', 'Changed Mind'),
        ('Found Better Price', 'Found Better Price'),
        ('Other', 'Other'),
    )

    user = models.ForeignKey(Account, on_delete = models.SET_NULL, null = True)
    payment = models.ForeignKey(Payment,on_delete = models.SET_NULL, null = True, blank = True)
    order_number = models.CharField(max_length = 20)
    user_profile = models.ForeignKey(UserProfile, on_delete=models.SET_NULL, null=True)
    shipping_address = models.ForeignKey(Address, related_name='shipping_address', on_delete=models.SET_NULL, null=True)
    billing_address = models.ForeignKey(Address, related_name='billing_address', on_delete=models.SET_NULL, null=True, blank=True)
    order_note = models.CharField(max_length = 100, blank = True)
    order_total = models.PositiveIntegerField()
    tax = models.PositiveIntegerField()
    status = models.CharField(max_length = 100 , choices = STATUS, default = 'Pending')
    ip = models.CharField(max_length = 10, blank = True)
    is_ordered = models.BooleanField(default = False)
    coupon = models.ForeignKey(Coupon, on_delete=models.SET_NULL, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)

    cancellation_reason = models.CharField(max_length=100, choices=CANCELLATION_REASONS, blank=True, null=True)
    return_reason = models.TextField(blank=True, null=True)


    def __str__(self):
        return self.user.first_name
    

class OrderProduct(models.Model):
    order = models.ForeignKey(Order,on_delete = models.CASCADE)
    payment = models.ForeignKey(Payment,on_delete = models.SET_NULL, blank = True, null = True)
    user = models.ForeignKey(Account,on_delete = models.CASCADE)
    product = models.ForeignKey(Product,on_delete = models.CASCADE)
    product_attribute = models.ForeignKey(ProductAttribute,on_delete = models.CASCADE)
    product_price = models.PositiveIntegerField()
    quantity = models.PositiveIntegerField()
    ordered = models.BooleanField(default = False)
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)

    def __str__(self):
        return self.product.name
    
class Wallet(models.Model):
    user = models.OneToOneField(Account, on_delete=models.CASCADE, null=True)
    amount = models.PositiveIntegerField(default=100)
    updated_at = models.DateTimeField(auto_now=True)


    def __str__(self):
        return f"Wallet for User : {self.user.first_name}"
    
class WalletTransaction(models.Model):
    wallet = models.ForeignKey(Wallet, on_delete=models.CASCADE)
    transaction_type = models.CharField(max_length=255, choices=[('Credit', 'Credit'), ('Debit', 'Debit')])
    amount = models.PositiveIntegerField()
    transaction_date = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return f"{self.wallet.user.first_name} - {self.transaction_type} - ${self.amount} - {self.transaction_date}"
 

accounts/forms.py
from django import forms
from .models import Account,UserProfile, Address

class RegistrationForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'Enter Password', 'class': 'form-control'}))
    confirm_password = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'Confirm Password', 'class': 'form-control'}))

    class Meta:
        model = Account
        fields = ('first_name', 'last_name', 'email', 'password')

    def __init__(self, *args, **kwargs): 
        super(RegistrationForm, self).__init__(*args, **kwargs)

        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.widget.attrs['placeholder'] = field_name.replace('_', ' ').title()

    def clean(self):
        cleaned_data = super(RegistrationForm, self).clean()
        password = cleaned_data.get('password')
        confirm_password = cleaned_data.get('confirm_password')

        if password != confirm_password:
            raise forms.ValidationError(
                'Password does not match'
            )

class UserForm(forms.ModelForm):
    class Meta:
        model = Account
        fields = ('first_name', 'last_name')

    def __init__(self, *args, **kwargs):
        super(UserForm, self).__init__(*args, **kwargs)

        for  field in self.fields:
            self.fields[field].widget.attrs['class'] = 'form-control'

class UserProfileForm(forms.ModelForm):
    profile_picture = forms.ImageField(required=False, error_messages={'invalid': 'Image Files Only'}, widget=forms.FileInput)

    class Meta:
        model = UserProfile
        fields = ( 'phone','profile_picture')

    def __init__(self, *args, **kwargs):
        super(UserProfileForm, self).__init__(*args, **kwargs)

        for field in self.fields:
            self.fields[field].widget.attrs['class'] = 'form-control'



class AddressForm(forms.ModelForm):
    class Meta:
        model = Address
        fields = ['address_line_1', 'address_line_2', 'country', 'state', 'district', 'postal_code']
       

templates/accounts/cancel_order_confirmation.html
{% extends "base.html" %}
{% load static %}
{% block content %}

<!-- Page Header Start -->
<div class="container-fluid bg-secondary mb-5">
	<div class="d-flex flex-column align-items-center justify-content-center" style="min-height: 170px">
		<h1 class="font-weight-semi-bold text-uppercase mb-3">Order Cancellation</h1>
		<div class="d-inline-flex">
			<p class="m-0"><a href="{% url "home" %}">Home</a></p>
			<p class="m-0 px-2">-</p>
			<p class="m-0">Order Cancellation</p>
		</div>
	</div>
</div>
<!-- Page Header End -->

<!-- ========================= SECTION CONTENT ========================= -->
<section class="section-conten padding-y bg">

<div class="container-fluid">
	<div class="row">
		<aside class="col-md-3">
			{% include "accounts/sidebar.html" %}
		</aside>
		<main class="col-md-9">
			<article class="card">
				<header class="card-header">
					<h5 class="card-title">Order Cancellation</h5>
				</header>
				<div class="card-body">
					<p>Are you sure you want to cancel this order?</p>
					<form method="post" action="{% url 'cancel_order_confirmation' order_id=order.id %}">
						{% csrf_token %}
						<div class="form-group col-5">
							<label for="id_cancellation_reason">Cancellation Reason:</label>
							<select name="cancellation_reason" id="id_cancellation_reason" class="form-control">
								{% for reason in form.cancellation_reason.field.choices %}
									<option value="{{ reason.0 }}">{{ reason.1 }}</option>
								{% endfor %}
							</select>
						</div> 
						<button type="submit" class="btn btn-danger">Confirm Cancellation</button>
						<a href="{% url 'my_orders'  %}" class="btn btn-secondary">Cancel</a>
					</form>
				</div>
			</article>
		</main>
	</div> <!-- row.// -->
</div>

</section>
<!-- ========================= SECTION CONTENT END// ========================= -->

{% endblock content %}

templates/accounts/dashboard.html
{% extends "base.html" %}
{% load static %}
{% block content %}

  <!-- Page Header Start -->
  <div class="container-fluid bg-secondary mb-5">
	<div class="d-flex flex-column align-items-center justify-content-center" style="min-height: 120px">
		<h1 class="font-weight-semi-bold text-uppercase mb-3">Dashboard</h1>
		<div class="d-inline-flex">
			<p class="m-0"><a href="{% url "home" %}">Home</a></p>
			<p class="m-0 px-2">-</p>
			<p class="m-0">Dashboard</p>
		</div>
	</div>
</div>
<!-- Page Header End -->

<!-- ========================= SECTION CONTENT ========================= -->
<section class="section-conten padding-y bg">

<div class="container-fluid ">
	<div class="row">
	<aside class="col-md-3">
		{% include "accounts/sidebar.html" %}
	</aside>
	<main class="col-md-9">
		<article class="card">
		<header class="card-header">
			<strong class="d-inline-block mr-3">Logged in as: </strong>
			<span>{{user.full_name}}</span>
		</header>
		<div class="card-body">
			<div class="row"> 
				<div class="col-md-6">
					<div class="card" style="text-align: center;">
						<div class="card-body">
							<h5 class="card-title">Total Orders</h5>
							<h4>{{orders_count}}</h4>
							<a href="{% url "my_orders" %}">View Orders</a>
						</div>
					</div>
				</div>
				<div class="col-md-6">
					<div class="card" style="text-align: center;">
						<div class="card-body">
							{% if userprofile.profile_picture %}
								<img src="{{ userprofile.profile_picture.url }}" alt="User Profile Picture" width="72" height="72" style="border-radius: 50%;border: 2px solid #D19C97;" class="avatar">			
							{% else %}
								<img src="https://www.w3schools.com/howto/img_avatar.png" alt="Default Profile Picture" width="72" height="72" style="border-radius: 50%;border: 2px solid #D19C97;" class="avatar">			
							{% endif %}
							<p class="mb-0">{{user.email}}</p>
							{% if userprofile.phone %}
								<p class="mb-0">Mobile no. : {{userprofile.phone}}</p>
							{% endif %}
						</div>
					</div> 
				</div>
				
			</div> <!-- row.// -->
		</div> <!-- card-body .// -->
		<div class="table-responsive">
		
		</div> <!-- table-responsive .end// -->
		</article> <!-- order-group.// --> 
	</main>
</div> <!-- row.// -->
</div>


</section>
<!-- ========================= SECTION CONTENT END// ========================= -->


{% endblock content %}

templates/accounts/district_dropdown_option.html
<option value="">---------</option>
{% for district in districts %}
<option value="{{ district.pk }}">{{ district.name }}</option>
{% endfor %}

templates/accounts/edit_Address.html
{% extends "base.html" %}
{% load static %}

{% block content %}

    <!-- Edit Address Form Start -->
    <section class="section-content padding-y">

        <div class="card mx-auto" style="max-width: 520px; margin-top: 40px;">
            <article class="card-body">
                {% include "alerts.html" %}
                <header class="mb-4 text-center"><h4 class="card-title text-primary">Edit Address</h4></header>
                    <form method="post" id="editAddressForm" data-cities-url="{% url 'ajax_load_district' %}">
                        {% csrf_token %}
                        <input type="hidden" name="address_id" value="{{ address.id }}">
                        <div class="row">
                            <div class="col-md-6 form-group">
                                <label for="id_address_line_1">Address Line 1</label>
                                <input id="id_address_line_1" class="form-control" type="text" name="address_line_1" value="{{ address.address_line_1 }}">
                            </div>
                            <div class="col-md-6 form-group">
                                <label for="id_address_line_2">Address Line 2</label>
                                <input id="id_address_line_2" class="form-control" type="text" name="address_line_2" value="{{ address.address_line_2 }}">
                            </div>
                            <div class="col-md-6 form-group">
                                <label for="id_country">Country</label>
                                <input class="form-control" type="text" name="country" value="{{ address.country }}" readonly>
                            </div>                            
                            <div class="col-md-6 form-group">
                                <label for="id_state">State</label>
                                <select id="id_state" class="custom-select" name="state">
                                    <option value="{{ address.state.id }}" selected>{{ address.state }}</option>
                                    {% for state in states %}
                                    <option value="{{ state.id }}">{{ state }}</option>
                                    {% endfor %}
                                </select>
                            </div>
                            <div class="col-md-6 form-group">
                                <label for="id_district">District</label>
                                <select id="id_district" class="custom-select" name="district">
                                    <option value="{{ address.district.id }}" selected>{{ address.district }}</option>
                                    <!-- Ajax-loaded districts will be added here dynamically -->
                                </select>
                            </div>
                            <div class="col-md-6 form-group">
                                <label for="id_postal_code">ZIP Code</label>
                                <input id="id_postal_code" class="form-control" type="text" name="postal_code" value="{{ address.postal_code }}">
                            </div>
                        </div>
                        <button type="submit" class="btn btn-primary">Save Changes</button>
                    </form>
                </article>
            </div>           
        </section>
    <!-- Edit Address Form End -->

    <!-- Ajax Script -->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script>
        $(document).ready(function () {
            $("#id_state").change(function () {
                const url = $("#editAddressForm").attr("data-cities-url");
                const stateId = $(this).val();

                $.ajax({
                    url: url,
                    data: {
                        'state_id': stateId
                    },
                    success: function (data) {
                        $("#id_district").html(data);
                    }
                });

            });
        });
    </script>

{% endblock content %}

templates/accounts/edit_profile.html
{% extends "base.html" %}
{% load static %}
{% block content %}

  <!-- Page Header Start -->
  <div class="container-fluid bg-secondary mb-5">
	<div class="d-flex flex-column align-items-center justify-content-center" style="min-height: 120px">
		<h1 class="font-weight-semi-bold text-uppercase mb-3">Dashboard</h1>
		<div class="d-inline-flex">
			<p class="m-0"><a href="{% url "home" %}">Home</a></p>
			<p class="m-0 px-2">-</p>
			<p class="m-0">Dashboard</p>
		</div>
	</div>
</div>
<!-- Page Header End -->

<!-- ========================= SECTION CONTENT ========================= -->
<section class="section-conten padding-y bg">
<div class="container-fluid ">
	<div class="row">
	<aside class="col-md-3">
		{% include "accounts/sidebar.html" %}
	</aside>
	<main class="col-md-9">
        {% include "alerts.html" %}
		<article class="card">
		<header class="card-header">
			<strong class="d-inline-block mr-3">Edit Profile</strong>
		</header>
		<div class="card-body">
            <div class="text-right">
                {% if userprofile.profile_picture %}
                    <img src="{{ userprofile.profile_picture.url }}" alt="User Profile Picture" width="100" height="100" style="border-radius: 50%;border: 2px solid #D19C97;" class="avatar">			
                {% else %}
                    <img src="https://www.w3schools.com/howto/img_avatar.png" alt="Default Profile Picture" width="100" height="100" style="border-radius: 50%;border: 2px solid #D19C97;" class="avatar">			
                {% endif %}
            </div>
			<div class="row"> 
				<div class="col-md-12">
					<form action="{% url "edit_profile" %}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-row">
                            <div class="form-group col-md-6">
                                <label for="">First Name</label>
                                {{user_form.first_name}}
                            </div>
                            <div class="form-group col-md-6">
                                <label for="">Last Name</label>
                                {{user_form.last_name}}
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="form-group col-md-6">
                                <label for="">Phone Number</label>
                                {{profile_form.phone}}
                            </div>
                            <div class="form-group col-md-6">
                                <label for="">Profile Picture</label>
                                {{profile_form.profile_picture}}
                            </div>
                        </div>          
                        <input type="submit" class="btn btn-primary  border-0 px-4" value="Save">
                    </form>
				</div>
				
			</div> <!-- row.// -->
		</div> <!-- card-body .// -->
		<div class="table-responsive">
		
		</div> <!-- table-responsive .end// -->
		</article> <!-- order-group.// --> 
	</main>
</div> <!-- row.// -->
</div>


</section>
<!-- ========================= SECTION CONTENT END// ========================= -->


{% endblock content %}

templates/accounts/login.html
{% extends "base.html" %}

{% block content %}
<section class="section-content padding-y">
    {% if request.GET.command == 'verification' %}
    <div class="container mx-auto alert alert-Info text-center" role="alert"style="max-width:1024px; margin-top:100px;">
        Thank you for registering with us.We have send you a verification email to your email address [{{request.GET.email}}]
        <br><br>
        Already verified? <a href="{% url 'login' %}">Login </a>
    </div>
    {% else %}

    <div class="card mx-auto" style="max-width: 520px; margin-top: 40px;">
        <article class="card-body">
            {% include "alerts.html" %}
            <header class="mb-4 text-center">
                <h4 class="card-title">Login</h4>
            </header>
            <form action="{% url 'login' %}" method="post">
                {% csrf_token %}
                
                <div class="form-group">
                    <input type="email" name="email" class="form-control" placeholder="Enter Email ">
                </div>
                
                <div class="form-group">
                    <input type="password" name="password" class="form-control" placeholder="Enter Password">
                </div>
                
                <div class="form-group d-flex">
                    <div class="ml-auto">
                        <a href="{% url "forgotpassword" %}" class="form-right">Forgot Password?</a>
                    </div>
                </div>
                
                <div class="form-group">
                    <button type="submit" class="btn btn-primary btn-block">Login</button>
                </div>
            </form>
        </article>
    </div>
    <p class="text-center mt-4">Already have an account? <a href="{% url 'register' %}">Register</a></p>
    {% endif %}
</section>
{% endblock content %}

templates/accounts/my_order.html
{% extends "base.html" %}
{% load static %}
{% block content %}

  <!-- Page Header Start -->
  <div class="container-fluid bg-secondary mb-5">
	<div class="d-flex flex-column align-items-center justify-content-center" style="min-height: 120px">
		<h1 class="font-weight-semi-bold text-uppercase mb-3">Dashboard</h1>
		<div class="d-inline-flex">
			<p class="m-0"><a href="{% url "home" %}">Home</a></p>
			<p class="m-0 px-2">-</p>
			<p class="m-0">Dashboard</p>
		</div>
	</div>
</div>
<!-- Page Header End -->

<!-- ========================= SECTION CONTENT ========================= -->
<section class="section-conten padding-y bg">

<div class="container-fluid ">
	<div class="row">
	<aside class="col-md-3">
		{% include "accounts/sidebar.html" %}
	</aside>
	<main class="col-md-9">
		<article class="card">
		<header class="card-header">
			<strong class="d-inline-block mr-3">Order History </strong>
		</header>
		<div class="card-body">
			<div class="row"> 
				<div class="col-md-12">
					<table class="table table-hover">
                        <thead>
                          <tr>
                            <th scope="col">Order #</th>
                            <th scope="col">Billing Name</th>
                            <th scope="col">Phone</th>
                            <th scope="col">Order Total</th>
							<th scope="col">Order Status</th>
							<th scope="col">Payment Status</th>
                            <th scope="col">Date</th>
							{% if order.status == 'Cancelled' %}
							<th scope="col">Action</th>
							{% endif %}
                          </tr>
                        </thead>
                        <tbody>
                            {% for order in orders %}
                          <tr>
                            <th scope="row"><a href="{% url "order_detail" order.order_number %}" >{{order.order_number}}</a></th>
                            <td>{{user.full_name}}</td>
                            <td>{{user.userprofile.phone}}</td>
                            <td>Rs {{order.order_total}}</td>
							<td>{{order.status}}</td>
							<td>{{order.payment.status}}</td>
                            <td>{{order.created_at|date:"d/m/Y"}}</td>
							
							<td>
								{% if order.status != 'Cancelled' and order.status != 'Delivered' and order.payment.status != '' %}
								<a href="{% url "cancel_order_confirmation" order.id %}" type="btn btn-primary" >Cancel</a>
								{% endif %}
								{% if order.status == 'Delivered' %}
									<a href="{% url 'return_order' order.id %}" class="btn btn-primary">Return</a>
								{% endif %}
							</td>
                          </tr>
                          {% endfor %}
                        </tbody>
                      </table>
				</div>
				
			</div> <!-- row.// -->
		</div> <!-- card-body .// -->
		<div class="table-responsive">
		
		</div> <!-- table-responsive .end// -->
		</article> <!-- order-group.// --> 
	</main>
</div> <!-- row.// -->
</div>


</section>
<!-- ========================= SECTION CONTENT END// ========================= -->


{% endblock content %}

templates/accounts/resetpassword_validation.html
{% autoescape off %}
Hi {{user.first_name}},
As requested,Please click on the link below to reset your Password:
"http://{{ domain }}{% url 'resetpassword_validate' uidb64=uid token=token %}"

If you think it's not you, please ignore this email.
{% endautoescape %}